<a href="https://colab.research.google.com/github/MAVRICK-1/tutorials/blob/main/tensorflow_lession_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [4]:
tenser_zero_dim = tf.constant(42)
print(tenser_zero_dim)

tf.Tensor(42, shape=(), dtype=int32)


In [2]:
tensor_one_dim = tf.constant([1,2,3])
print(tensor_one_dim)


tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In the line tensor_one_dim = tf.constant([1,2,3]), tf.constant is a function that creates a TensorFlow constant tensor.

**Reasoning**:

- **TensorFlow**: TensorFlow is a library for numerical computation,
particularly well-suited for machine learning tasks.
- **Tensor**: In TensorFlow, a tensor is a multi-dimensional array of elements representing data. It's the fundamental building block.
- **Constant**: A constant tensor is a tensor whose value is fixed and cannot be changed during program execution.

In simpler terms:

Imagine a container that holds data. tf.constant creates this container, and you fill it with the values [1,2,3]. This container is now a constant, meaning the values inside cannot be changed.

In the given code: tensor_one_dim = tf.constant([1,2,3]) creates a one-dimensional constant tensor named tensor_one_dim and initializes it with the values 1, 2, and 3.

In [3]:
tensor_two_dim = tf.constant([[1,2,3],[4,5,6]])
print(tensor_two_dim)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [5]:
tensor_three_dim = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(tensor_three_dim)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)


Explanation:

tf.Tensor: This indicates that the output is a TensorFlow Tensor object. Tensors are the fundamental data structures in TensorFlow.

`[[[ 1 2 3] [ 4 5 6]] [[ 7 8 9] [10 11 12]]]`: This represents the actual data within the tensor. It's a 3-dimensional array with the values you provided in the code.

`shape=(2, 2, 3)`: This describes the dimensions of the tensor. It means the tensor has:

outer arrays (the first level)

Each outer array contains 2 inner arrays (the second level)
Each inner array has 3 elements (the third level)
dtype=int32: This specifies the data type of the elements in the tensor, which is 32-bit integers in this case.

In simpler terms:

Imagine a container (the tensor) that holds other containers. Inside the main container are 2 boxes. Each of those boxes contains 2 smaller boxes, and each smaller box holds 3 numbers (1, 2, 3, etc.). The shape tells us how many boxes and sub-boxes there are, and the dtype tells us what type of data is stored in the smallest boxes (in this case, integers).

In [8]:
print(tensor_three_dim.shape)
print(tensor_three_dim.dtype)
print(tensor_three_dim.ndim)
print(type(tensor_three_dim))

(2, 2, 3)
<dtype: 'int32'>
3
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [9]:
tensorflow_cast = tf.constant([2.,0.,8,7],dtype=tf.float16)
tensorflow_cast_int = tf.cast(tensorflow_cast,dtype=tf.int16)
tensorflow_cast_bool = tf.cast(tensorflow_cast,dtype=tf.bool)
print(tensorflow_cast)
print(tensorflow_cast_int)
print(tensorflow_cast_bool)

tf.Tensor([2. 0. 8. 7.], shape=(4,), dtype=float16)
tf.Tensor([2 0 8 7], shape=(4,), dtype=int16)
tf.Tensor([ True False  True  True], shape=(4,), dtype=bool)


In [10]:
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32)
print(numpy_A)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [11]:
converted_tensor = tf.convert_to_tensor(numpy_A)
print(converted_tensor)

tf.Tensor([ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24], shape=(24,), dtype=int32)


In [12]:
eye_tensor = tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None)
print(eye_tensor)


tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
